--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TwistedAsylumMC/MultiEconomy
branches:
- master
projects:
  MultiEconomy:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.0
...
